### ISSUE TITLE
Is GTK# in active state or dead?

### ISSUE THREAD

**Issue by gsmental** [jsuarezruiz/forms-gtk-progress#12]
I am watching this project for many months, but there is no change in this project.

**Comment by jsuarezruiz** [comment]
Still **active**, of course. What happens is that the issues and PR are managed from the official repository of Xamarin.Forms: [https://github.com/xamarin/Xamarin.Forms/pulls?q=is%3Apr+is%3Aclosed+label%3Ap%2Fgtk](https://github.com/xamarin/Xamarin.Forms/pulls?q=is%3Apr+is%3Aclosed+label%3Ap%2Fgtk)

**Comment by tluyben** [comment]
Are you working on this still or are other people. I have tried many things , but I cannot get it to work under Windows, basically because there is no gtk-sharp-2 anymore and most of the libraries for Windows for gtk-sharp-2 are hard to use, incompatible with many things and so forth. It seems the world moved to GTKSharp which is GTK 3.  That all seems stable and to work well with the pacman setup process. 

Do you know what the plans are for going for GTK  3 (GtkSharp) and possibly making it so that it works with the standard NuGet packages and 64 bit repositories?

**Comment by tluyben** [comment]
(sorry, saw this question was already asked, but I found this question while searching if GTK Forms was alive or not)

**Comment by jsuarezruiz** [comment]
Good questions. Yes, I'm still working on the project, continue adding support to new features as well as bug fixes. I'm not the only one doing PRs and applying improvements or fixes to the GTK backend. Any member of the community can help.

Related to GTK 3. Soon the backend will use an official gtk sharp 2.12 NuGet package. Currently everything works on Windows, macOS and Linux although you must install gtk sharp on each system and add references by hand. The NuGet package will avoid steps and possibly problems. As soon as we have the GTK3 bindings completed at the official level (official NuGet, etc), we will propose to update the Xamarin.Forms GTK backend to version 3. Meanwhile, it is based on version 2.12.

**Comment by tluyben** [comment]
Ok, thank you for the explanation. I did the install and added the references, but the projects keep crashing with some dll loading issue; if I compile with AnyCPU, it cannot load gtk-sharp-win32-2.12.dll (which is the one recommended install as far as I can find); if I compile with x86, then my project dll will not load (even though it is just hello world). It goes further than your demo projects, none of which compile because none of the dependencies can be found on nuget (of the particular versions you use).

Is there a 64bit version of 2.12 gtk-sharp or a nuget package I am missing? I cannot figure it out ;( It works fine under Linux by the way.

**Comment by tluyben** [comment]
Ignore the previous stuff; it was some DLL hell :( Apparently there is a lot of stuff on my laptop which adds it's directories to the PATH and have GTK / GLIB stuff in it. I started VS with the PATH in a batch file and all works now. Hope the future will make this easier!

**Comment by jsuarezruiz** [comment]
Thanks!
