### ISSUE TITLE
DisplayActionSheet and slider control

### ISSUE THREAD

**Issue by RogerHardiman** [jsuarezruiz/forms-gtk-progress#5]
Hi
Found a few bugs in the DisplayActionSheet and Slider Control.
I wondered if you wanted to add these to your status page. I've generated a pull request on the PlainConcepts fork of Xamarin Forms.

DisplayActionSheet has a problem when there are lots of buttons, e.g. 15 or more. The popup window is too tall for the screen and some buttons and the cancel button are off the edge of the screen.

The slider shows the numerical value (a GTK widget feature). Sliders on other platforms (Droid, iOS) do not show this so for consistency this needs to be removed.

I've done pull requests for both.

Thanks
Roger

**Comment by jsuarezruiz** [comment]
Hi @RogerHardiman,

First of all thanks for your support and help!. Will review the PR.

At the first point, you're right. DisplayActionSheet to have more buttons makes the screen grow. Depending on the size of the screen could fit buttons outside. Ideally, use Scroll. This bug was in the macOS backend as well and it is nice change.

Related to Slider control,  it is true that the numerical value is not shown in iOS and Android. However, in UWP appears the value in a popup by default. Maybe we should add consistency with iOS and Android. And I'll add a Platform Specifics to allow you to display the value.

Thanks!

Regards.

**Comment by RogerHardiman** [comment]
Hi
Thanks for looking at the Pull Request.
I found the DisplayActionSheet bug on macOS and wrote the fix. Then found GTK was the same. @rmarinho suggested the scroll area be 60% of the screen height so I used the same value in GTK.

For the Slider, if UWP shows the value then we could leave it in the GTK project and we can ignore the part of the PR.

**Comment by jsuarezruiz** [comment]
Will merge the DisplayActionSheet changes and ignore the Slider changes.
Thanks!

**Comment by RogerHardiman** [comment]
That is great. Thanks.
